### ISSUE TITLE
IDEA: Use png, svg, or any other image format too, or passing a react element 

### ISSUE THREAD

**Issue by kritik-sah** [tsAppDevelopment/react-icon-cloud#8] opened 2024-07-25 17:47 UTC

**Comment by teaguestockwell** [comment] 2024-12-29 05:38
1. pngs / jpegs
    - can be rendered under anchor tags like this: https://github.com/magicuidesign/magicui/blob/main/registry/default/magicui/icon-cloud.tsx
1. svgs
    - consider reusing [renderSimpleIcon](https://github.com/teaguestockwell/react-icon-cloud?tab=readme-ov-file#rendersimpleicon) or creating your own redner
1. react elements 
    - duplicate of #2

**Closed as completed by teaguestockwell** 2024-12-29 05:38 UTC
